### ISSUE TITLE
能不能release一个32位的apk？

### ISSUE THREAD

**Issue by howard868** [jadehh/FongMiTV#1]
能不能出个32位的？64位的安装不了。谢啦

**Comment by jadehh** [comment]
看下release,有问题再提

**Comment by jadehh** [comment]
就是这个版本不知道会不会被合并到正式版本中

**Comment by howard868** [comment]
看到了，多谢大佬。希望FongMi的正式版可以把这个merge一下

**Comment by jadehh** [comment]
> 看到了，多谢大佬。希望FongMi的正式版可以把这个merge一下

你多测下吧，看看有没有什么其他bug

**Comment by howard868** [comment]
> > 看到了，多谢大佬。希望FongMi的正式版可以把这个merge一下
> 
> 你多测下吧，看看有没有什么其他bug

好的
