### ISSUE TITLE
您好，求教自动更新，地址在那个文件更改啊？

### ISSUE THREAD

**Issue by ne7359** [jadehh/FongMiTV#15]
您好，求教自动更新，地址在那个文件更改啊？
                                                谢谢您

**Comment by jadehh** [comment]
什么自动更新

**Comment by ne7359** [comment]
客户端，手机端 电视TV端，只要新版本出来后，就会跳出来更新提示，包括更新了什么信息，跳出来的页面下面有点击下载更新，那怕我们在app/build.gradle更改版本号等，也会跳出更新信息，让你点击下载安装

跳出的信息：
```
[共通]
* 备份还原逻辑更改
* 一键配置 
* 一键恢复
从其他设备恢复数据 
[点播]
AI去广优化
迅雷缓存设置
[直播]
支持回看源
[推送]
支持接收手机推送APK文件
* 推送壁纸
```

跳出升级应该是读取 https://github.com/FongMi/Release/blob/main/apk/release/mobile.json

从这个地址下载更新：

https://github.com/FongMi/Release/tree/main/apk/release

**Comment by jadehh** [comment]
你把启动自动更新的代码去了就行了

**Comment by ne7359** [comment]
请教一下自动更新，在那个文件夹下那个文件，那段代码，谢谢您

最好是自动更新地址，麻烦您了

**Comment by jadehh** [comment]
你是想去掉启动时自动更新吗

**Comment by ne7359** [comment]
是啊，自己编译，就是想DIY，

如果告诉我链接那个文件更好，去掉启动时自动更新次子

二者有其一就行，麻烦您了哦

**Comment by jadehh** [comment]
## TV端
https://github.com/jadehh/FongMiTV/blob/467f683d8086ef83188c8dd3a00d373f807ea457/app/src/leanback/java/com/fongmi/android/tv/ui/activity/HomeActivity.java#L113

## Mobile
https://github.com/jadehh/FongMiTV/blob/467f683d8086ef83188c8dd3a00d373f807ea457/app/src/mobile/java/com/fongmi/android/tv/ui/activity/MainActivity.java#L66

> 这两句注释掉应该就行了，我没测。

**Comment by ne7359** [comment]
由衷的感谢您的帮助，谢谢了
