### ISSUE TITLE
您好：dev下settings.gradle下的core_settings.gradle代码其实就是编译Pyramid

### ISSUE THREAD

**Issue by ne7359** [jadehh/FongMiTV#16]
dev下settings.gradle下的core_settings.gradle代码其实就是编译Pyramid

所以我们编译出来的PY版与JAVA容量一样大，所以不支持PY

麻烦您修改一下core_settings.gradle，下面是编译Pyramid，因为我只懂皮毛，谢谢您了

下面链接是原来Pyramid源代码下有settings.gradle

https://github.com/UndCover/Pyramid

**Comment by jadehh** [comment]
## App Gradle
https://github.com/FongMi/TV/blob/f5ef745c3426d108c3a9776ea42f426816c81272/app/build.gradle#L105

## Setting Gradle
https://github.com/FongMi/TV/blob/f5ef745c3426d108c3a9776ea42f426816c81272/settings.gradle#L31

> 这两段才是支持Py编译的。在Release分支中加入下面两句应该就行了，Fongmi Releasa版本好像去掉了py的支持

**Comment by ne7359** [comment]
是的，但是没有构建py的settings.gradle文件就不会构建py的，所以加了这二句就无法编译apk，最后一句是/media/core_settings.gradle指向的就是构建py的settings.gradle文件。之于/media/core_settings.gradle我查找了很多也问ai绝对是用于第三方构建的

所以直接编译Releasa，不支持py，没有app/libs/pyramid.aar，容量就不一样，加入py的https://github.com/FongMi/Release/blob/main/apk/release/leanback-python-arm64_v8a.apk 是40.8 MB,

https://github.com/FongMi/Release/blob/main/apk/release/leanback-java-arm64_v8a.apk是29.1 MB。这是我们编译的ok版影视

---

这是FongMi版
https://github.com/FongMi/Release/blob/fongmi/apk/release/leanback-java-arm64_v8a.apk是23.6 MB

https://github.com/FongMi/Release/blob/fongmi/apk/release/leanback-python-arm64_v8a.apk是35.4 MB

下面地址是最早的py
https://github.com/UndCover/Pyramid

这是编译好的Pyramid网址
https://github.com/UndCover/PyramidStore

这是以前用于tvbox
```
#!/bin/bash
echo '添加PY支持'
wget --no-check-certificate -qO- "https://raw.githubusercontent.com/UndCover/PyramidStore/main/aar/pyramid-1011.aar" -O app/libs/pyramid.aar
sed -i "/thunder.jar/a\    implementation files('libs@pyramid.aar')" app/build.gradle
sed -i 's#@#\\#g' app/build.gradle
sed -i 's#pyramid#\\pyramid#g' app/build.gradle
echo "" >> app/proguard-rules.pro
echo "#添加PY支持" >> app/proguard-rules.pro
echo "-keep public class com.undcover.freedom.pyramid.** { *; }" >> app/proguard-rules.pro
echo "-dontwarn com.undcover.freedom.pyramid.**" >> app/proguard-rules.pro
echo "-keep public class com.chaquo.python.** { *; }" >> app/proguard-rules.pro
echo "-dontwarn com.chaquo.python.**" >> app/proguard-rules.pro
sed -i '/import com.orhanobut.hawk.Hawk;/a\import com.undcover.freedom.pyramid.PythonLoader;' app/src/main/java/com/github/tvbox/osc/base/App.java
sed -i '/import com.orhanobut.hawk.Hawk;/a\import com.github.catvod.crawler.SpiderNull;' app/src/main/java/com/github/tvbox/osc/base/App.java
sed -i '/PlayerHelper.init/a\        PythonLoader.getInstance().setApplication(this);' app/src/main/java/com/github/tvbox/osc/base/App.java
sed -i '/import android.util.Base64;/a\import com.github.catvod.crawler.SpiderNull;' app/src/main/java/com/github/tvbox/osc/api/ApiConfig.java
sed -i '/import android.util.Base64;/a\import com.undcover.freedom.pyramid.PythonLoader;' app/src/main/java/com/github/tvbox/osc/api/ApiConfig.java
sed -i '/private void parseJson(String apiUrl, String jsonStr)/a\        PythonLoader.getInstance().setConfig(jsonStr);' app/src/main/java/com/github/tvbox/osc/api/ApiConfig.java
sed -i '/public Spider getCSP(SourceBean sourceBean)/a\        if (sourceBean.getApi().startsWith(\"py_\")) {\n        try {\n            return PythonLoader.getInstance().getSpider(sourceBean.getKey(), sourceBean.getExt());\n        } catch (Exception e) {\n            e.printStackTrace();\n            return new SpiderNull();\n        }\n    }' app/src/main/java/com/github/tvbox/osc/api/ApiConfig.java
sed -i '/public Object\[\] proxyLoca/a\    try {\n        if(param.containsKey(\"api\")){\n            String doStr = param.get(\"do\").toString();\n            if(doStr.equals(\"ck\"))\n                return PythonLoader.getInstance().proxyLocal(\"\",\"\",param);\n            SourceBean sourceBean = ApiConfig.get().getSource(doStr);\n            return PythonLoader.getInstance().proxyLocal(sourceBean.getKey(),sourceBean.getExt(),param);\n        }else{\n            String doStr = param.get(\"do\").toString();\n            if(doStr.equals(\"live\")) return PythonLoader.getInstance().proxyLocal(\"\",\"\",param);\n        }\n    } catch (Exception e) {\n        e.printStackTrace();\n    }\n' app/src/main/java/com/github/tvbox/osc/api/ApiConfig.java
echo '添加PY支持完成'
```

**Comment by ne7359** [comment]
这是AI告诉我的，主要用于构建APK插件构建
gradle.ext.androidxMediaModulePrefix = 'media-'
apply from: file("path to/core_settings.gradle")

**Comment by jadehh** [comment]
首先这个插件不是构建py的，这肯定是视频相关的库。不要纠结于Dev分支，只关注release分支是，可以编译成py的，只是Fomgmi去掉了。稍等我给你个版本。

**Comment by ne7359** [comment]
绝对无法编译带PY的

**Comment by ne7359** [comment]
用于构建APK插件构建
gradle.ext.androidxMediaModulePrefix = 'media-'
apply from: file("path to/core_settings.gradle")
也100%绝对用于编译PY的

**Comment by ne7359** [comment]
如想带PY，也可以用这个方法，但是这个版本老

工作流自动
```
env:
    GITHUB_WORKSPACE: ${{ github.workspace }}
    GRADLE_TASKS: assembleLeanbackPythonArm64_v8aRelease assembleLeanbackPythonArmeabi_v7aRelease assembleMobilePythonArm64_v8aRelease assembleMobilePythonArmeabi_v7aRelease

      - name: diy
        if: contains(env.GRADLE_TASKS, matrix.framework)
        working-directory: tv
        run: |
           $GITHUB_WORKSPACE/add-py.sh

```
#!/bin/bash
echo '添加PY支持'
wget --no-check-certificate -qO- "https://raw.githubusercontent.com/UndCover/PyramidStore/main/aar/pyramid-1011.aar" -O app/libs/pyramid.aar
sed -i "/thunder.jar/a\    implementation files('libs@pyramid.aar')" app/build.gradle
sed -i 's#@#\\#g' app/build.gradle
sed -i 's#pyramid#\\pyramid#g' app/build.gradle
echo "" >> app/proguard-rules.pro
echo "#添加PY支持" >> app/proguard-rules.pro
echo "-keep public class com.undcover.freedom.pyramid.** { *; }" >> app/proguard-rules.pro
echo "-dontwarn com.undcover.freedom.pyramid.**" >> app/proguard-rules.pro
echo "-keep public class com.chaquo.python.** { *; }" >> app/proguard-rules.pro
echo "-dontwarn com.chaquo.python.**" >> app/proguard-rules.pro
sed -i '/import com.orhanobut.hawk.Hawk;/a\import com.undcover.freedom.pyramid.PythonLoader;' app/src/main/java/com/github/tvbox/osc/base/App.java
sed -i '/import com.orhanobut.hawk.Hawk;/a\import com.github.catvod.crawler.SpiderNull;' app/src/main/java/com/github/tvbox/osc/base/App.java
sed -i '/PlayerHelper.init/a\        PythonLoader.getInstance().setApplication(this);' app/src/main/java/com/github/tvbox/osc/base/App.java
sed -i '/import android.util.Base64;/a\import com.github.catvod.crawler.SpiderNull;' app/src/main/java/com/github/tvbox/osc/api/ApiConfig.java
sed -i '/import android.util.Base64;/a\import com.undcover.freedom.pyramid.PythonLoader;' app/src/main/java/com/github/tvbox/osc/api/ApiConfig.java
sed -i '/private void parseJson(String apiUrl, String jsonStr)/a\        PythonLoader.getInstance().setConfig(jsonStr);' app/src/main/java/com/github/tvbox/osc/api/ApiConfig.java
sed -i '/public Spider getCSP(SourceBean sourceBean)/a\        if (sourceBean.getApi().startsWith(\"py_\")) {\n        try {\n            return PythonLoader.getInstance().getSpider(sourceBean.getKey(), sourceBean.getExt());\n        } catch (Exception e) {\n            e.printStackTrace();\n            return new SpiderNull();\n        }\n    }' app/src/main/java/com/github/tvbox/osc/api/ApiConfig.java
sed -i '/public Object\[\] proxyLoca/a\    try {\n        if(param.containsKey(\"api\")){\n            String doStr = param.get(\"do\").toString();\n            if(doStr.equals(\"ck\"))\n                return PythonLoader.getInstance().proxyLocal(\"\",\"\",param);\n            SourceBean sourceBean = ApiConfig.get().getSource(doStr);\n            return PythonLoader.getInstance().proxyLocal(sourceBean.getKey(),sourceBean.getExt(),param);\n        }else{\n            String doStr = param.get(\"do\").toString();\n            if(doStr.equals(\"live\")) return PythonLoader.getInstance().proxyLocal(\"\",\"\",param);\n        }\n    } catch (Exception e) {\n        e.printStackTrace();\n    }\n' app/src/main/java/com/github/tvbox/osc/api/ApiConfig.java
echo '添加PY支持完成'
```

**Comment by jadehh** [comment]
你的意思是我release中的py Apk有问题，我刚对比了下确实是，因为我用的自动发布没注意py版本。

**Comment by ne7359** [comment]
是的，所以带那个
```
gradle.ext.androidxMediaModulePrefix = 'media-'
apply from: file("path to/core_settings.gradle")
```
就能自动编译PY插件，然后编译

**Comment by ne7359** [comment]
至于编译还需要什么源码，这是开发者老的源码网址，https://github.com/UndCover/Pyramid

您懂，不像我小白，所以无法写settings.gradle也就是core_settings.gradle

**Comment by jadehh** [comment]
https://github.com/jadehh/FongMiTV/tree/py 看下这个分支吧，基于release分支改了几个gradle文件, release文件夹下有编译好的apk文件

**Comment by jadehh** [comment]
https://github.com/jadehh/FongMiTV/tree/release/pyramid 这个作者本来就集成了

**Comment by ne7359** [comment]
https://github.com/jadehh/FongMiTV/tree/release/pyramid 这个作者本来就集成了
根本就没有编译的啊，用于编译的，所以要core_settings.gradle

**Comment by jadehh** [comment]
py不需要这个啊

**Comment by jadehh** [comment]
我没用到core_settings.gradle 这个一样还是生成了 py Apk

**Comment by ne7359** [comment]
是啊，这样，您写一下core_settings.gradle就非常简单了，这样就可以编译fongmi与测试版了

**Comment by jadehh** [comment]
不考虑发布测试版

**Comment by ne7359** [comment]
谢谢您，呵呵总是打扰您
