### ISSUE TITLE
您看一下，我们编译的电视版本与ok影视  影视APK的大小容量居然差几十兆，手机版基本上一样

### ISSUE THREAD

**Issue by ne7359** [jadehh/FongMiTV#17]
https://github.com/FongMi/Release/tree/main
我们的代码拉取的是上面的
https://github.com/FongMi/Release/tree/fongmi

**Comment by jadehh** [comment]
https://github.com/jadehh/FongMiTV/blob/467f683d8086ef83188c8dd3a00d373f807ea457/app/build.gradle#L76

> 主要在这段TV打包默认需要载入x5内核，如果不需要的话可以去掉

**Comment by ne7359** [comment]
哦，原来是这样啊，谢谢您

**Comment by ne7359** [comment]
请教x5内核，是支持什么的啊？完成不懂！！！！！！
