### ISSUE TITLE
你好 收藏跟历史同步 TV端无法选中设备

### ISSUE THREAD

**Issue by hcwsky** [jadehh/FongMiTV#18]
你好 收藏跟历史同步 TV端无法选中设备

**Comment by jadehh** [comment]
我这边是正常的呀，你是遥控器无法控制吗

**Comment by hcwsky** [comment]
是啊 遥控器无法上下选中设备 只能接鼠标点击

**Comment by hcwsky** [comment]
> 我这边是正常的呀，你是遥控器无法控制吗

你好 这种有办法修复吗？不然这个功能形同虚设啊 TV端根本无法选中扫描出来的设备。

**Comment by jadehh** [comment]
> 你好 这种有办法修复吗？不然这个功能形同虚设啊 TV端根本无法选中扫描出来的设备。

没有你的电视型号，不好做测试，过段时间换个通用的UI吧，现在直接用的手机端的，可能会存在这个问题

**Comment by hcwsky** [comment]
> > 你好 这种有办法修复吗？不然这个功能形同虚设啊 TV端根本无法选中扫描出来的设备。
> 
> 没有你的电视型号，不好做测试，过段时间换个通用的UI吧，现在直接用的手机端的，可能会存在这个问题

TV端都不行啊 我试了很多不同品牌的电视 都是无法选中扫描出来的设备 包括模拟器也测试过了 期待你的完善

**Comment by jadehh** [comment]
能截个图或者录个视频看下吗，我这边用模拟器是可以操作的，刷新按钮和同步设备都是能实现的。你能加载出同一局域网的设备吗?

**Comment by jadehh** [comment]
这是我用两个模拟器组的局域网测得，是能选中的，刷新按钮也正常。
![1717661446918](https://github.com/jadehh/FongMiTV/assets/20532462/6d54096c-e261-4979-87bc-78fa8f4505a1)
> 你的是刷新按钮都不能点吗，整个Dialog都无法选中的状态吗

**Comment by jadehh** [comment]
#2 这个别人也测过能正常进行同步的呀

**Comment by hcwsky** [comment]
你没明白我的意思，点击，同步啥的都是正常的。就是键盘或者遥控器上下无法选中扫描处理的设备。
比如向这样有选中后的焦点
![image](https://github.com/jadehh/FongMiTV/assets/144415881/66dd0810-b4ec-409f-b635-fc54efc7739b)

**Comment by jadehh** [comment]
先跟你确认下，就是选中后你无法看出，但是点击确认是可以同步的是吧，如果有多个设备，你根本不知道你选中的是哪个设备吧，只能看运气随便选一个同步，是这样吗。

**Comment by hcwsky** [comment]
不是，用鼠标选中点击都没问题。就是TV端遥控器根本没有焦点可以选中设备，包括用模拟器键盘也是无法上下选择设备进行同步。OK的手机端那个上传下载的功能，扫描出来的设备是可以用模拟器键盘上下选中设备的。

**Comment by jadehh** [comment]
哦哦这就难办了，我用模拟器测试和电视测试都是可以的，没有其他的电视设备了。

**Comment by hcwsky** [comment]
你的电视可以正常选中设备进行同步？奇怪了 我试了很多台设备都是不行，你能否发个apk给我试试。

**Comment by jadehh** [comment]
大概知道是什么原因，先发个版本，只能麻烦你到时候在测下了。

**Comment by hcwsky** [comment]
没问题 随时可以测试

**Comment by jadehh** [comment]
https://github.com/jadehh/FongMiTV/releases/tag/v2.4.1 试下这个版本的呢

**Comment by hcwsky** [comment]
现在可以了，完美。
