### ISSUE TITLE
多设备同步收藏和播放历史

### ISSUE THREAD

**Issue by howard868** [jadehh/FongMiTV#2]
希望能增加同步收藏和播放历史的功能，觉得这个比较难实现，但会是很实用的功能。远端数据同步服务器不太好搞，也许局域网内服务器比较容易些？

**Comment by jadehh** [comment]
好的后续考虑加入这个功能

**Comment by jadehh** [comment]
写的过程中发现，这个功能在mobile上已经实现了，支持双向同步的。
![image](https://github.com/jadehh/FongMiTV/assets/20532462/f64f25ba-25b9-4f2d-a79c-8f0115d5768e)

**Comment by howard868** [comment]
额。可以支持多个电视之间同步吗？比如我的客厅电视和卧室的电视相互同步。代码可以复制到电视版的app吗？还有个问题是我没有安卓手机，所以只能依靠电视设备间同步了。

**Comment by jadehh** [comment]
好的，后续TV加入同步功能

**Comment by jadehh** [comment]
## 同步
* 加入历史，收藏同步功能
![1715687545492](https://github.com/jadehh/FongMiTV/assets/20532462/452d6d72-9b12-4c7a-a52a-e2e36eeb4328)

**Comment by howard868** [comment]
太感谢了 我回家后测试一下

**Comment by howard868** [comment]
点了同步的按钮 然后再点选择装置 就没反应了

**Comment by jadehh** [comment]
截图，或者录个视频看下你怎么操作的。

**Comment by jadehh** [comment]
是找不到局域网的设备吗。

**Comment by jadehh** [comment]
* 确保两个设备都处于开启状态并且打开TV App
* 确保两个设备的IP，只有末位地址不一样，如: 192.168.0.110  192.168.0.220
> 跨网段的ip地址是无法搜到的,如:192.168.1.110 192.168.0.220
![1715736215728](https://github.com/jadehh/FongMiTV/assets/20532462/10019835-5538-4581-a9d5-f0c3d4da42b2)

**Comment by howard868** [comment]
我同时打开了两个电视的app 相互之间看不到 如图![image](https://github.com/jadehh/FongMiTV/assets/122852334/0de3a3ae-e3de-4f95-a8d3-fdaae41024d6)

两个电视的ip是同一个ip段的

**Comment by jadehh** [comment]
最好确认下两个电视的ip地址

**Comment by howard868** [comment]
终于可以同步了 两个设备都重启一下就好了 刚才估计是网络问题
