### ISSUE TITLE
荐片线路 exo解码无法播放

### ISSUE THREAD

**Issue by WoKee** [jadehh/FongMiTV#6]
你好，请问下。下载了程序安装，荐片线路 exo解码无法播放，ijk可以。 
但是原版影视exo解码正常播放。exo这块有什么需要调整的地方吗？

**Comment by jadehh** [comment]
这块代码我没动，exo，系统，和 ijk 我都没搞清楚。

**Comment by WoKee** [comment]
> 这块代码我没动，exo，系统，和 ijk 我都没搞清楚。

嗯，fongmi源码编译的也不行。。只有他编译过的apk可以， 不知道是不是这部分没有开源？

**Comment by jadehh** [comment]
可以看下其他分支是否支持，比如dev或fongmi分支

**Comment by WoKee** [comment]
> 可以看下其他分支是否支持，比如dev或fongmi分支

感谢回复，其他分支的exo相关的代码没有开源。 不知道有没有解决办法

**Comment by jadehh** [comment]
顺便问下为什么一定要用 exo 解码呢。

**Comment by WoKee** [comment]
> 顺便问下为什么一定要用 exo 解码呢。

exo使用的系统解码拓展，可以根据硬件特性解码 杜比视界等（ijk不行，单纯的系统解码支持的解码格式较少）。 而且解码出来的画质很通透。IJK 在很多电视上 性能比较弱，会卡顿，优先exo是比较理想的。

**Comment by jadehh** [comment]
了解，我一直以为ijk比exo更流畅呢。
